#!/bin/sh

if [ $# -ne 1 ]; then
	echo "Usage: `basename $0` [project name]"
	exit 1
else
	name=$1
fi

# TODO: Check that the project name has no special chars that shouldn't
# be in a directory name or in a CL symbol (that is, would require escaping)
# Or maybe warn the user and then create a directory friendly name, like
# github does with new repos
mkdir $name
cd $name

# package.lisp
echo "\
(defpackage :$name
  (:include :cl))" > package.lisp

# Prompt user for description
temp=`mktemp`
echo > $temp
echo Enter a brief description of your project on the line above >> $temp
echo Only the first line of this file is used >> $temp

# Check if $EDITOR is set
if [ -z "$EDITOR" ]; then
	echo NOTE: '$EDITOR' is unset: defaulting to nano >> $temp
	nano $temp
else
	$EDITOR $temp
fi

head -1 $temp > README.md

rm $temp
